name: Run Python Script on Schedule

on:
  # GitHub cron is in UTC. Two lines below run at 07:00 Europe/Warsaw year-round
  # by covering both DST states (UTC+1 and UTC+2):
  schedule:
  - cron: '10 18 * * 2-6'
  - cron: '10 19 * * 2-6'
  workflow_dispatch:       # lets you run it manually from the Actions tab

concurrency:
  group: supabase-cron
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: python-scheduled-job
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python backend/upload/currency.py

